name: "pr-size-labeler"
description: "This set a label using a T-Shirt size model"
inputs:
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
  l_max_size:
    description: "Max size for a PR to be considered L"
    required: false
    default: "1000"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.l_max_size }}
